# Generated by Django 5.2.5 on 2025-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquetePolitique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(max_length=150)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur'), ('aucun', 'Aucun')], max_length=20, null=True)),
                ('region', models.CharField(max_length=100)),
                ('departement', models.CharField(default='Danané', editable=False, max_length=100)),
                ('commune', models.CharField(choices=[('Danané', 'Danané'), ('Daleu', 'Daleu'), ('Kouan-Houlé', 'Kouan-Houlé'), ('Gbon-Houyé', 'Gbon-Houyé'), ('Seileu', 'Seileu')], max_length=100)),
                ('lieu_vote', models.CharField(max_length=150)),
                ('carte_electeur', models.CharField(blank=True, max_length=50, null=True)),
                ('parti', models.CharField(max_length=100)),
                ('candidat', models.CharField(max_length=100)),
                ('attentes', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
