# Generated by Django 4.2.23 on 2025-08-31 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enqueteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquêteur',
                'verbose_name_plural': 'Enquêteurs',
            },
        ),
        migrations.CreateModel(
            name='FicheMilitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('departement_administratif', models.CharField(max_length=100, verbose_name='Département Administratif')),
                ('departement', models.CharField(default='Danané', max_length=100, verbose_name='Département')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('qualite_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualité dans la section')),
                ('comite_base', models.CharField(max_length=100, verbose_name='Comité de base')),
                ('qualite_cb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualité dans le CB')),
                ('fonction_parti', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction dans le Parti')),
                ('lieu_vote', models.CharField(max_length=150, verbose_name='Lieu de vote')),
                ('poste_electif', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste électif')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('contacts', models.CharField(max_length=100, verbose_name='Contact(s)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('profession', models.CharField(max_length=150, verbose_name='Profession')),
                ('fonction', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction')),
                ('inscription_electorale', models.CharField(choices=[('inscrit', 'Inscrit sur la liste électorale'), ('non_inscrit', 'Non inscrit sur la liste électorale')], max_length=15, verbose_name='Inscription électorale')),
                ('a_cni', models.BooleanField(default=False, verbose_name="Carte Nationale d'Identité (CNI)")),
                ('a_attestation', models.BooleanField(default=False, verbose_name="Attestation d'identité")),
                ('a_certificat', models.BooleanField(default=False, verbose_name='Certificat de Nationalité')),
                ('a_extrait', models.BooleanField(default=False, verbose_name='Extrait de Naissance')),
                ('a_recepisse', models.BooleanField(default=False, verbose_name='Récépissé Nouvelle CNI')),
                ('aucune_piece', models.BooleanField(default=False, verbose_name='Aucune Pièce')),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de la pièce')),
                ('numero_carte_electeur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro carte électeur')),
                ('nni', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'Identification Unique (NNI)")),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('est_dans_csv', models.BooleanField(default=False, verbose_name='Présent dans le fichier électoral')),
                ('numero_electeur_csv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro électeur trouvé')),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_militant', to='ficheMilitant.enqueteur')),
            ],
            options={
                'verbose_name': 'Fiche de Militant',
                'verbose_name_plural': 'Fiches de Militants',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='EnquetePolitique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(max_length=150)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('superieur', 'Supérieur'), ('aucun', 'Aucun')], max_length=20, null=True)),
                ('region', models.CharField(max_length=100)),
                ('departement', models.CharField(default='Danané', editable=False, max_length=100)),
                ('commune', models.CharField(choices=[('Danané', 'Danané'), ('Daleu', 'Daleu'), ('Kouan-Houlé', 'Kouan-Houlé'), ('Gbon-Houyé', 'Gbon-Houyé'), ('Seileu', 'Seileu')], max_length=100)),
                ('lieu_vote', models.CharField(max_length=150)),
                ('carte_electeur', models.CharField(blank=True, max_length=50, null=True)),
                ('parti', models.CharField(max_length=100)),
                ('candidat', models.CharField(max_length=100)),
                ('attentes', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='ficheMilitant.enqueteur')),
            ],
            options={
                'verbose_name': 'Enquête Politique',
                'verbose_name_plural': 'Enquêtes Politiques',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
