# Generated by Django 4.2.23 on 2025-09-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemilitant',
            name='fonction_parti',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='poste_electif',
        ),
    ]
