# Generated by Django 5.2.5 on 2025-08-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0002_alter_enquetepolitique_options_enqueteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheMilitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('departement_administratif', models.CharField(max_length=100, verbose_name='Département Administratif')),
                ('departement', models.CharField(default='Danané', max_length=100, verbose_name='Département')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('qualite_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualité dans la section')),
                ('comite_base', models.CharField(max_length=100, verbose_name='Comité de base')),
                ('qualite_cb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualité dans le CB')),
                ('fonction_parti', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction dans le Parti')),
                ('lieu_vote', models.CharField(max_length=150, verbose_name='Lieu de vote')),
                ('poste_electif', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste électif')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('contacts', models.CharField(max_length=100, verbose_name='Contact(s)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('profession', models.CharField(max_length=150, verbose_name='Profession')),
                ('fonction', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction')),
                ('inscription_electorale', models.CharField(choices=[('inscrit', 'Inscrit sur la liste électorale'), ('non_inscrit', 'Non inscrit sur la liste électorale')], max_length=15, verbose_name='Inscription électorale')),
                ('a_cni', models.BooleanField(default=False, verbose_name="Carte Nationale d'Identité (CNI)")),
                ('a_attestation', models.BooleanField(default=False, verbose_name="Attestation d'identité")),
                ('a_certificat', models.BooleanField(default=False, verbose_name='Certificat de Nationalité')),
                ('a_extrait', models.BooleanField(default=False, verbose_name='Extrait de Naissance')),
                ('a_recepisse', models.BooleanField(default=False, verbose_name='Récépissé Nouvelle CNI')),
                ('aucune_piece', models.BooleanField(default=False, verbose_name='Aucune Pièce')),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de la pièce')),
                ('numero_carte_electeur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro carte électeur')),
                ('nni', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'Identification Unique (NNI)")),
                ('presidium', models.BooleanField(default=False, verbose_name='Présidium')),
                ('conseil_politique', models.BooleanField(default=False, verbose_name='Conseil Politique')),
                ('directoire', models.BooleanField(default=False, verbose_name='Directoire')),
                ('secretariat_executif', models.BooleanField(default=False, verbose_name='Secrétariat Exécutif')),
                ('bureau_politique', models.BooleanField(default=False, verbose_name='Bureau Politique')),
                ('conseil_national', models.BooleanField(default=False, verbose_name='Conseil National')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('enqueteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_militant', to='ficheMilitant.enqueteur')),
            ],
            options={
                'verbose_name': 'Fiche de Militant',
                'verbose_name_plural': 'Fiches de Militants',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
