# Generated by Django 4.2.23 on 2025-09-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0002_remove_fichemilitant_fonction_parti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemilitant',
            name='photo',
            field=models.TextField(blank=True, help_text='Photo encodée en base64', null=True, verbose_name='Photo (Base64)'),
        ),
    ]
