# Generated by Django 5.2.5 on 2025-08-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0003_fichemilitant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemilitant',
            name='bureau_politique',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='conseil_national',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='conseil_politique',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='directoire',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='presidium',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='secretariat_executif',
        ),
    ]
