# Generated by Django 4.2.23 on 2025-09-04 22:56

from django.db import migrations, models
import ficheMilitant.models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0003_fichemilitant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichemilitant',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du militant (formats supportés: JPG, PNG, WebP)', null=True, upload_to=ficheMilitant.models.upload_photo_path, verbose_name='Photo'),
        ),
    ]
