# Generated by Django 4.2.23 on 2025-09-04 23:42

from django.db import migrations, models
import ficheMilitant.models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0004_alter_fichemilitant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichemilitant',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo d'identité du militant (facultatif)", null=True, upload_to=ficheMilitant.models.upload_photo_path, verbose_name='Photo du militant'),
        ),
    ]
