# Generated by Django 5.2.5 on 2025-08-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0004_remove_fichemilitant_bureau_politique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemilitant',
            name='est_dans_csv',
            field=models.BooleanField(default=False, verbose_name='Présent dans le fichier électoral'),
        ),
        migrations.AddField(
            model_name='fichemilitant',
            name='numero_electeur_csv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro électeur trouvé'),
        ),
    ]
