# Generated by Django 4.2.23 on 2025-09-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0005_alter_fichemilitant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemilitant',
            name='departement_administratif',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='region',
        ),
    ]
