# Generated by Django 4.2.23 on 2025-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0006_remove_fichemilitant_departement_administratif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichemilitant',
            name='lieu_vote',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu de vote'),
        ),
        migrations.AlterField(
            model_name='fichemilitant',
            name='zone',
            field=models.CharField(blank=True, choices=[('', 'Sélectionner une zone'), ('DALEU', 'Daleu'), ('DANANE', 'Danané'), ('DANANE SP', 'Danané SP'), ('GBON-HOUYE', 'Gbon-Houyé'), ('KOUAN-HOULE', 'Kouan-Houlé'), ('SEILEU', 'Seileu')], max_length=100, null=True, verbose_name='Zone'),
        ),
    ]
