# Generated by Django 4.2.23 on 2025-09-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0007_alter_fichemilitant_lieu_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichemilitant',
            name='lieu_vote',
            field=models.CharField(default=0, max_length=150, verbose_name='Lieu de vote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichemilitant',
            name='zone',
            field=models.CharField(choices=[('DALEU', 'Daleu'), ('DANANE', 'Danané'), ('DANANE SP', 'Danané SP'), ('GBON-HOUYE', 'Gbon-Houyé'), ('KOUAN-HOULE', 'Kouan-Houlé'), ('SEILEU', 'Seileu')], max_length=100, verbose_name='Zone'),
        ),
    ]
