# Generated by Django 4.2.23 on 2025-09-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0008_alter_fichemilitant_lieu_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemilitant',
            name='nni',
        ),
        migrations.RemoveField(
            model_name='fichemilitant',
            name='numero_carte_electeur',
        ),
    ]
