# Generated by Django 4.2.23 on 2025-09-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0009_remove_fichemilitant_nni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichemilitant',
            name='fonction',
        ),
    ]
