# Generated by Django 5.2.7 on 2025-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheMilitant', '0010_remove_fichemilitant_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichemilitant',
            name='fonction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='fichemilitant',
            name='nni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'Identification Unique (NNI)"),
        ),
        migrations.AddField(
            model_name='fichemilitant',
            name='numero_carte_electeur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro carte électeur'),
        ),
        migrations.AlterField(
            model_name='enquetepolitique',
            name='commune',
            field=models.CharField(choices=[('Man', 'Man')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquetepolitique',
            name='departement',
            field=models.CharField(default='Man', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='fichemilitant',
            name='departement',
            field=models.CharField(default='Man', max_length=100, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='fichemilitant',
            name='zone',
            field=models.CharField(choices=[('MAN', 'Man')], max_length=100, verbose_name='Zone'),
        ),
    ]
